import test from 'node:test';
import assert from 'node:assert/strict';
import { normalize,auditEvidence,profileSchema,defaultProfile,hash,samDate } from '../netlify/functions/_shared/core.ts';
const analysis=()=>({recommendation:'pursue' as const,fitScore:95,summary:'Fit',scope:[],rationale:[],blockers:[],unknowns:[],dates:[],requirements:[],economics:'Unknown',nextAction:'Review',coverage:'Scope only'});
test('SAM normalization keeps missing budget/deadlines unknown and rejects unsafe IDs',()=>{const n=normalize({noticeId:'abc123456789',title:'Test',fullParentPathName:'Agency'});assert.equal(n.deadline,'');assert.equal(n.setAside,'Not specified');assert.equal(n.url,'https://sam.gov/opp/abc123456789/view');assert.throws(()=>normalize({noticeId:'../../secret'}));});
test('unsupported evidence cannot establish compliance or a pursue recommendation',()=>{const a=analysis();const result=auditEvidence({...a,requirements:[{requirement:'Certification',status:'met',source:'Scope',quote:'Invented qualification'}]},[{name:'Scope',text:'Perform a penetration test.'}]);assert.equal(result.requirements[0].status,'unverified');assert.equal(result.recommendation,'review');assert.equal(result.warnings.length,1);});
test('a mandatory gap overrides a strong fit score',()=>{const a=analysis();const result=auditEvidence({...a,requirements:[{requirement:'Facility clearance',status:'gap',source:'Scope',quote:'A facility clearance is required.'}]},[{name:'Scope',text:'A facility clearance is required.'}]);assert.equal(result.recommendation,'review');assert.equal(result.fitScore,95);});
test('valid source evidence is retained and profile contains no assumed qualifications',()=>{const a=analysis();const result=auditEvidence({...a,requirements:[{requirement:'Remote work',status:'met',source:'Scope',quote:'Remote work is permitted.'}]},[{name:'Scope',text:'Remote work is permitted.'}]);assert.equal(result.warnings.length,0);assert.equal(profileSchema.parse(defaultProfile()).automation,false);});
test('source revisions are deterministic and UTC dates match SAM syntax',()=>{assert.equal(hash('x'),hash('x'));assert.notEqual(hash('x'),hash('y'));assert.equal(samDate(new Date('2026-10-01T00:00:00Z')),'10/01/2026');});
