import {test} from 'node:test';import assert from 'node:assert/strict';
import {auditExtraction} from '../netlify/functions/_shared/intake';
test('unsupported facts are removed and missing availability stays unknown',()=>{const result=auditExtraction({profile:{name:'Jane Doe',email:'invented@example.com',clearance:'Top Secret'},evidence:[{field:'name',quote:'Jane Doe'},{field:'clearance',quote:'Made up claim'}],warnings:[]},'Jane Doe\nCloud engineer');assert.equal(result.profile.email,'');assert.equal(result.profile.clearance,'');assert.equal(result.profile.availability,'unknown');assert.equal(result.evidence.length,1);});
test('exact quoted claims are retained for human validation',()=>{const r=auditExtraction({profile:{name:'Jane Doe',skills:'Cloud security'},evidence:[{field:'name',quote:'Jane Doe'},{field:'skills',quote:'Cloud security'}],warnings:[]},'Jane Doe\nCloud security');assert.equal(r.profile.skills,'Cloud security');});

test('one malformed model field cannot discard the remaining draft',()=>{const r=auditExtraction({profile:{name:'Jane Doe',email:'not an email',availability:'Available',skills:'Cloud security'},evidence:[{field:'name',quote:'Jane Doe'},{field:'skills',quote:'Cloud security'}],warnings:[]},'Jane Doe\nCloud security');assert.equal(r.profile.name,'Jane Doe');assert.equal(r.profile.skills,'Cloud security');assert.equal(r.profile.email,'');assert.equal(r.profile.availability,'unknown');assert.equal(r.warnings.length,2);});

test('PDF line wrapping and bullet glyphs do not discard supported evidence',()=>{const r=auditExtraction({profile:{name:'Jane Doe',skills:'Cloud security'},evidence:[{field:'name',quote:'Jane Doe'},{field:'skills',quote:'Cloud security and network operations'}],warnings:[]},'Jane Doe\n Cloud security\nand network operations');assert.equal(r.profile.skills,'Cloud security');assert.equal(r.evidence.length,2);});

test('supported resume sections fill skills and experience without inventing facts',()=>{const text='Jane Doe\nTECHNICAL SKILLS\nCloud security, Python\nWORK EXPERIENCE\nEngineer at Example\nEDUCATION\nDegree';const r=auditExtraction({profile:{name:'Jane Doe',skills:'unsupported summary'},evidence:[{field:'name',quote:'Jane Doe'}],warnings:[]},text);assert.equal(r.profile.skills,'Cloud security, Python');assert.equal(r.profile.experience,'Engineer at Example');assert.ok(r.evidence.every(e=>text.includes(e.quote)));});
