const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(action,body){const r=await fetch(`/api/resume-intake/${action}`,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed.');return data;}
export async function intakePage({root,openModal,toast,demo=false}){
 root.innerHTML=`<div class="page-heading"><div><h1>Resume intake</h1><p>Email resumes to partners@marked.solutions. Review drafts before adding partners.</p></div><div class="actions"><button class="secondary" id="recover-intake">Check recent emails</button><button class="secondary" id="refresh-intake">Refresh</button></div></div><div class="panel"><label>View<select id="intake-view"><option value="pending">Pending review</option><option value="all">All submissions</option></select></label><div id="intake-list" role="status">Loading…</div></div>`;
 let items=[];const draw=()=>{const view=root.querySelector('#intake-view').value,visible=items.filter(i=>view==='all'||!['approved','rejected'].includes(i.status));root.querySelector('#intake-list').innerHTML=visible.length?visible.map(i=>`<button class="partner-card" data-intake="${esc(i.id)}"><h2>${esc(i.name)}</h2><span class="badge">${esc(i.status==='pending'?'Pending review':i.status)}</span><p>${esc(i.sender)} · ${esc(new Date(i.createdAt).toLocaleString())}</p>${i.error?`<p class="form-error">${esc(i.error)}</p>`:''}</button>`).join(''):'<div class="empty"><h2>No submissions in this view</h2><p>Incoming resumes will appear here. Use Refresh to check processing progress.</p></div>';root.querySelectorAll('[data-intake]').forEach(b=>b.onclick=()=>review(b.dataset.intake));};
 const refresh=async()=>{try{if(demo){items=[];draw();return;}const data=await request('list');items=data.items;draw();if(!data.configured)toast('Email intake needs its Resend credentials configured.',true);}catch(e){root.querySelector('#intake-list').textContent=e.message;}};
 const review=async id=>{try{
  const {item}=await request(`detail?id=${encodeURIComponent(id)}`),p=item.profile||{},editable=['pending','error'].includes(item.status);
  const response=await fetch('/api/partners/list'),data=await response.json();if(!response.ok)throw Error(data.error||'Could not load partners.');const pool=data.partners;
  const fields=[['name','Name',150],['email','Email',254],['company','Company',200],['skills','Skills',6000],['certifications','Certifications (claimed)',4000],['clearance','Clearance (claimed)',1000],['experience','Experience',8000],['location','Location',300],['availabilityNotes','Availability details',2000],['rateNotes','Rate notes',1000],['notes','Internal notes',4000]];
  openModal(`<h1>Review resume</h1><p>${esc(item.name)} · ${esc(item.sender)}</p><div class="review-grid"><section><a class="secondary" href="/api/resume-intake/resume?id=${encodeURIComponent(id)}">Download original resume</a><h2>Resume text</h2><pre class="resume-review-text">${esc(item.resumeText||'Text extraction did not complete. Review the original attachment.')}</pre>${(item.warnings||[]).map(w=>`<p class="form-error">${esc(w)}</p>`).join('')}</section><form id="intake-form">${fields.map(([key,title,max])=>`<label>${title}<textarea name="${key}" maxlength="${max}" rows="${['skills','experience'].includes(key)?3:1}" ${!editable?'disabled':''} ${key==='name'?'required minlength="2"':''}>${esc(p[key]||'')}</textarea></label>${(item.evidence||[]).filter(e=>e.field===key).map(e=>`<blockquote class="small muted">${esc(e.quote)}</blockquote>`).join('')}`).join('')}<label>Availability<select name="availability" ${!editable?'disabled':''}>${['unknown','available','limited','unavailable'].map(v=>`<option ${p.availability===v?'selected':''} value="${v}">${v}</option>`).join('')}</select></label>${editable?`<label>Add or merge<select name="partnerId"><option value="">Create new partner</option>${pool.map(p=>`<option value="${esc(p.id)}">Merge into ${esc(p.name)} (${esc(p.email)})</option>`).join('')}</select></label><p class="small muted">Merging replaces profile fields with the reviewed values and saves this resume. Approval does not independently verify credentials or clearance.</p><button class="primary full" type="submit">Approve partner</button><button class="secondary" type="button" id="reject-intake">Reject submission</button>${item.status==='error'?'<button class="secondary" type="button" id="retry-intake">Retry extraction</button>':''}`:`<p>Status: ${esc(item.status)}</p>`}<p id="review-error" class="form-error" role="alert"></p></form></div>`,true);
  const form=document.querySelector('#intake-form'),error=form.querySelector('#review-error');
  if(editable){const action=async(name,body)=>{const buttons=form.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await request(name,body);document.querySelector('#modal').close();await refresh();toast(name==='approve'?'Partner approved. Reanalyze opportunities to use the updated pool.':name==='retry'?'Extraction requested. Refresh to check progress.':'Submission rejected.');}catch(e){error.textContent=e.message;buttons.forEach(b=>b.disabled=false);}};
   form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),profile=Object.fromEntries(f);delete profile.partnerId;action('approve',{id,profile,partnerId:f.get('partnerId')});};
   form.querySelector('#reject-intake').onclick=()=>action('reject',{id});if(form.querySelector('#retry-intake'))form.querySelector('#retry-intake').onclick=()=>action('retry',{id});}
 }catch(e){toast(e.message,true);}};
 root.querySelector('#recover-intake').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{if(demo)throw Error('Sign in to check incoming resumes.');await request('recover-recent',{});await refresh();toast('Recent resumes checked. Refresh to see extraction progress.');}catch(e){toast(e.message,true);}finally{button.disabled=false;}};
 root.querySelector('#refresh-intake').onclick=refresh;root.querySelector('#intake-view').onchange=draw;await refresh();
}
